In [2]:
import pandas as pd
from assets.utils.txt import append_to_txt, read_txt

row = read_txt("./data/custom_movie_rating.txt")
column_names = ["CustomID", "MovieID", "MovieName", "Rating"]
custom_movie_rating_df = pd.DataFrame(row, columns=column_names)

column_names = ["MovieID", "CustomID", "Comment", "Rating", "N_Likes"]
row = read_txt("./data/movie_comments.txt")
movie_comments_df = pd.DataFrame(row, columns=column_names)

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

In [2]:
import csv

custom_movie_rating_df.to_csv(
    "./custom_movie_rating.csv",
    index=False,  # 인덱스 제외
    quoting=csv.QUOTE_ALL,  # 모든 필드를 따옴표로 감싸기
    escapechar="\\",  # 특수 문자 이스케이프
    doublequote=True,  # 이중 따옴표 허용
)

In [3]:
import csv

movie_comments_df.to_csv(
    "./movie_comments.csv",
    index=False,  # 인덱스 제외
    quoting=csv.QUOTE_ALL,  # 모든 필드를 따옴표로 감싸기
    escapechar="\\",  # 특수 문자 이스케이프
    doublequote=True,  # 이중 따옴표 허용
)

In [3]:
row = read_txt("./data/movie_info_watcha.txt")
column_names = [
    "MovieID",
    "Title",
    "Year",
    "Genre",
    "Country",
    "Runtime",
    "Age",
    "Cast_Production_Info_List",
    "Synopsis",
    "Avg_Rating",
    "N_Rating(만명)",
    "N_Comments",
]
movie_info = pd.DataFrame(row, columns=column_names)

In [4]:
movie_info.to_csv("./movie_info_watch.csv", index=False)

In [7]:
pd.read_csv(
    "/Users/visuworks/Desktop/ST2L/HappyNewYear/data_scraping/custom_movie_rating.csv"
)

              CustomID  MovieID     MovieName  Rating
0        ZBm5R0Mj7qd46  m5XKVDL         양자물리학     3.0
1        ZBm5R0Mj7qd46  m5Nn2GE       영화로운 작음     3.5
2        ZBm5R0Mj7qd46  mWvq0vZ           내 방     2.5
3        ZBm5R0Mj7qd46  mdKpyBk      성적표의 김민영     3.0
4        ZBm5R0Mj7qd46  mOopbwm  킹덤4: 대장군의 귀환     3.0
...                ...      ...           ...     ...
7048510  ZBm5RPQa3qd46  mWpmAMO         어린 신부     3.0
7048511  ZBm5RPQa3qd46  mJ5x9BW          8 마일     4.0
7048512  ZBm5RPQa3qd46  my5YvvW       어거스트 러쉬     3.0
7048513  ZBm5RPQa3qd46  m85Xwpd     번지 점프를 하다     4.0
7048514  ZBm5RPQa3qd46  mQO8A2d          이클립스     1.0

[7048515 rows x 4 columns]

In [ ]:
pd.read_csv(
    "/Users/visuworks/Desktop/ST2L/HappyNewYear/data_scraping/movie_comments.csv"
)

,MovieID,CustomID,Comment,Rating,N_Likes
0,m5XKVDL,yKZx3nJg254dJ,"""양자물리학""이라는 제목만 빼고 전반적으로 다 괜찮은 영화. . . #현시점대한민국...",3.0,152
1,m5XKVDL,nkPvrb8wrvgar,"안녕하세요, 물리학과입니다. 이런게 물리라면 저는 문과입니다. Never quite...",2.0,141
2,m5XKVDL,yKZx37WjDx4dJ,양자물리학을 억지로 개연성도 없이 영화에 삽입시키고있다 검사님 연기 리스펙,2.5,128
3,m5XKVDL,6ewxakKkyvQ1m,검사 연기가 후덜덜 특히 곽철용과의 씬들이 재밌는데 거의 검사실 몰카 보는 수준이다...,4.0,97
4,m5XKVDL,Qgy51rmX7xDjk,우아는커녕 추잡스럽게.,2.0,91
...,...,...,...,...,...
1781666,m5mY4jD,4WLxZQ2bm5roA,전문 배우와 비전문 배우의 합 더 자주 보고 싶음 한국 영화는 배우 캐스팅 구조가 ...,3.0,1
1781667,m5mY4jD,8BRvepzLVmq6V,뭐 좋아해? 심플한데 반짝거리는거? 이 영화같은거!!,4.5,1
1781668,m5mY4jD,j4PxOwzB4oxp0,찬란을 꿈꾸는 심장들의 영원한 덜컹거림.,4.0,0
1781669,m5mY4jD,Pznx9KOKWv761,보조바퀴 보다는 이불킥이라는 제목이 더 어울리는 영화 - 2022.11.11. ...,2.0,0
1781670,m5mY4jD,4WLxZkkJlEqro,8.25 12 6 --- 0개 22.11.12,보는 중,0

In [9]:
pd.read_csv(
    "/Users/visuworks/Desktop/ST2L/HappyNewYear/data_scraping/movie_info_watch.csv"
)

,MovieID,Title,Year,Genre,Country,Runtime,Age,Cast_Production_Info_List,Synopsis,Avg_Rating,N_Rating(만명),N_Comments
0,m45nEnd,사마리아,2004.0,드라마,한국,1시간 35분,청불,"[('김기덕', '감독'), ('이얼', '주연 | 영기'), ('곽지민', '주연...","""인도에 바수밀다 라는 창녀가 있었어. 그런데 그 창녀랑 잠만 자고 나면 남자들이 ...",2.8,3.4,500+\n
1,mWLjGNd,택시 드라이버,1976.0,드라마 스릴러,미국,1시간 53분,청불,"[('마틴 스콜세지', '감독'), ('로버트 드 니로', '주연 | 트래비스'),...",트래비스(로버트 드 니로)는 베트남전에서 귀환한 후 불면증에 시달리며 사회에 적응하...,4.0,10.8,4000+\n
2,mOk6BPQ,파울볼,2014.0,다큐멘터리,한국,1시간 27분,전체,"[('조정래', '감독'), ('김보경', '감독'), ('조진웅', '나레이션')...","한,미,일 3개국 프로야구 선수 출신 최향남, 국내 프로야구 신인왕 출신 김수경 등...",3.3,7355.0,500+\n
3,mdBzPGd,청설,2009.0,드라마 로맨스,대만,1시간 49분,전체,"[('청펀펀', '감독'), ('펑위옌', '주연 | 티엔커'), ('진의함', '...",손으로 말하는 ‘양양’과 그녀에게 첫눈에 반한 ‘티엔커’. 마음이 듣고 가슴으로 느...,3.8,16.5,2000+\n
4,mObJJRO,하녀 라본느,NaN,NaN,NaN,1시간 22분,청불,"[('살바토르 샘페리', '감독'), ('플로랑스 구에린', '주연'), ('트린 ...",NaN,2.5,36.0,10+\n
...,...,...,...,...,...,...,...,...,...,...,...,...
50124,m5r3yXo,프레셔스 헤어 & 뷰티,2021.0,단편,영국,11분,NaN,"[('존 오건무이와이와', '감독')]",NaN,2.8,2.0,None\n
50125,m5Y63Zl,전원일기:젖소농장새댁,2015.0,성인 로맨스,한국,1시간 31분,청불,"[('한동호', '감독'), ('신건석', '주연'), ('임송이', '주연')]",젖소농장에서 열심히 일을 하며 하루하루를 보내는 동길. 어느 날 동길이 일하고 있는...,1.6,130.0,10+\n
50126,mWvw3Gx,"아나, 내사랑",2017.0,드라마,"루마니아, 프랑스",2시간 7분,NaN,"[('칼린 페터 네쩌', '감독'), ('다이아나 카발리오티', '주연 | 아나')...",대학생 아나와 토마는 첫눈에 사랑에 빠지고 뜨거운 격정으로 서로를 탐닉한다. 부모의...,2.5,37.0,7\n
50127,mdj24nJ,메크툽 마이 러브: 앵떼르메조,2019.0,드라마 코미디,"이탈리아, 프랑스",3시간 32분,NaN,"[('압델라티프 케시시', '감독'), ('샤인 부메딘', '주연 | 아민'), (...",NaN,2.8,18.0,4\n
50128,mO2MDzQ,앨리스 오어 더 라스트 에스커페이드,1977.0,판타지,프랑스,1시간 33분,NaN,"[('끌로드 샤브롤', '감독'), ('실비아 크리스텔', '주연 | 앨리스 카롤'...",NaN,3.6,21.0,10+\n